defaults:
  - default
  - override cluster: example
  - override dataset: flores200.ablation.v4.2
  - override model_type: dense

train_prefix: "dense"
validate_interval_updates: 20000
encoder_langtok: "src"
ddp_backend: "fully_sharded"
lr: 0.004
warmup: 8000
max_tokens: 8192
update_freq: 2
num_nodes: 8
num_gpus_per_node: 8
temp: 1
dropout: 0
max_time_mins: 4320
