dataset:
  max_video_len: 256
  max_len: 64
  split: test
  meta_processor: SignCLIPMetaProcessor
  video_processor: SignCLIPPoseProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  data_dir: /shares/volk.cl.uzh/zifjia/tensorflow_datasets
  test_datasets: [
    ['asl_signs', '1.0.0', '1.0.0-uzh'],
    ['asl_citizen', '1.0.0'],
    ['sem_lex', '1.0.0'],
  ]
  test_path: data/<dataset>/test.txt # placeholder, no use
  test_separately: true
  sp_universal_tagging: true
  test_in_vocab: true
  aligner: DSAligner
  pose_components: 'reduced_face'
  # anonym_pose: true
slurm_config: big
task_type: local_predict
fairseq:
  dataset:
    # batch_size: 256
    batch_size: 512
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/retri_v1_1/baseline_final/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 609
eval:
  save_path: runs/retri_v1_1/baseline_final/eval
metric: RWTHFSMetric
predictor: RetrievalPredictor
