sed -i -e 's/_arb_/_ara_/g' $1
sed -i -e 's/_azj_/_aze_/g' $1
sed -i -e 's/_pes_/_fas_/g' $1
sed -i -e 's/_fuv_/_ful_/g' $1
sed -i -e 's/_lvs_/_lav_/g' $1
sed -i -e 's/_khk_/_mon_/g' $1
sed -i -e 's/_zsm_/_zlm_/g' $1
sed -i -e 's/_gaz_/_orm_/g' $1
sed -i -e 's/_pbt_/_pus_/g' $1
sed -i -e 's/_uzn_/_uzb_/g' $1
sed -i -e 's/_zho_/_cmn_/g' $1